from manim import *

class QuadraticFormula(Scene):
    def construct(self):
        myTemplate = TexTemplate()
        myTemplate.add_to_preamble(r"\usepackage{amssymb}")
        myTemplate.add_to_preamble(r"\usepackage{amsmath}")
        myTemplate.add_to_preamble(r"\usepackage{mathfonts}")
        name = Text("1308 김현성")
        equation1 = MathTex(r"ax^2 + bx + c = 0")
        equation2 = MathTex(r"ax^2 + bx = -c")
        equation3 = MathTex(r"x^2 + \frac{b}{a}x = -\frac{c}{a}")
        equation4 = MathTex(r"x^2 + \frac{b}{a}x + (\frac{1}{2}\times\frac{b}{a})^2 = -\frac{c}{a} + (\frac{1}{2}\times\frac{b}{a})^2")
        equation5 = MathTex(r"x^2 + \frac{b}{a}x + (\frac{b}{2a})^2 = -\frac{c}{a} + (\frac{b}{2a})^2")
        equation6 = MathTex(r"(x + \frac{b}{2a})^2 = -\frac{c}{a} + (\frac{b}{2a})^2")
        equation7 = MathTex(r"(x + \frac{b}{2a})^2 = -\frac{c}{a} + \frac{b^2}{4a^2}")
        equation8 = MathTex(r"(x + \frac{b}{2a})^2 = -\frac{4ac}{4a^2} + \frac{b^2}{4a^2}")
        equation9 = MathTex(r"(x + \frac{b}{2a})^2 = \frac{b^2-4ac}{4a^2}")
        equation10 = MathTex(r"\sqrt{(x + \frac{b}{2a})^2} = \sqrt{\frac{b^2-4ac}{4a^2}}")
        equation11 = MathTex(r"x + \frac{b}{2a} = \frac{\pm \sqrt{b^2-4ac}}{2a}")
        equation12 = MathTex(r"x = \frac{\pm \sqrt{b^2-4ac}}{2a} - \frac{b}{2a}")
        equation13 = MathTex(r"x = \frac{-b \pm \sqrt{b^2-4ac}}{2a}")

        self.play(Write(name), run_time = 2)
        self.wait(1)
        self.play(name.animate.scale(0.5).to_edge(UL), run_time = 2)
        self.wait(1)
        self.play(Write(equation1), run_time = 3)
        self.play(ReplacementTransform(equation1, equation2), run_time = 2)
        self.wait(1)
        self.play(ReplacementTransform(equation2, equation3), run_time = 2)
        self.wait(1)
        self.play(ReplacementTransform(equation3, equation4), run_time = 2)
        self.wait(2)
        self.play(ReplacementTransform(equation4, equation5), run_time = 2)
        self.wait(2)
        self.play(ReplacementTransform(equation5, equation6), run_time = 2)
        self.wait(1)
        self.play(ReplacementTransform(equation6, equation7), run_time = 2)
        self.wait(1)
        self.play(ReplacementTransform(equation7, equation8), run_time = 2)
        self.wait(1)
        self.play(ReplacementTransform(equation8, equation9), run_time = 2)
        self.wait(1)
        self.play(ReplacementTransform(equation9, equation10), run_time = 2)
        self.wait(1)
        self.play(ReplacementTransform(equation10, equation11), run_time = 2)
        self.wait(1)
        self.play(ReplacementTransform(equation11, equation12), run_time = 2)
        self.wait(1)
        self.play(ReplacementTransform(equation12, equation13), run_time = 2)
        self.wait(1)
        self.play(
            equation13.animate.shift(DOWN), 
            run_time = 1
        )
        final = MathTex(r"\therefore \text{When } ax^2 + bx + c = 0,").to_edge(UP, buff = 3)
        self.play(Write(final), run_time = 2)
        self.wait(1)
        self.play(FadeOut(final), FadeOut(name), FadeOut(equation13), run_time = 4)